# Generated by Django 4.1.6 on 2023-02-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=20.0),
            preserve_default=False,
        ),
    ]
