# Generated by Django 4.1.6 on 2023-02-17 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='create',
            new_name='created_at',
        ),
    ]
